name = "DynamicallyLoadedEmbedding"
uuid = "bb81f446-86f5-47d0-8ffc-7ac2adc264fd"
authors = ["Gunnar Farnebäck <gunnar.farneback@contextvision.se>"]
version = "0.2.0"

[compat]
Clang_jll = "14, 15"
julia = "1"

[extras]
Clang_jll = "0ee61d77-7f21-5576-8119-9fcc46b10100"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Clang_jll", "Libdl", "Test"]
