name = "DynamicallyLoadedEmbedding"
uuid = "bb81f446-86f5-47d0-8ffc-7ac2adc264fd"
authors = ["Gunnar Farnebäck <gunnar.farneback@contextvision.se>"]
version = "0.1.1"

[deps]

[compat]
julia = "1"
PackageCompiler = "1.2"

[extras]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Libdl", "PackageCompiler", "Test"]
